[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "dist"

[dev]
  command = "npm run dev"
  targetPort = 8080
  port = 8888

# Genel API yönlendirmeleri silindi

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# HTTP başlık tanımlamaları
[[headers]]
  for = "/api/card-reader"
  [headers.values]
    # CORS ayarları
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    # SSL yönlendirmesi devre dışı
    Strict-Transport-Security = "max-age=0"
