[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "dist"

[dev]
  command = "npm run dev"
  targetPort = 8080
  port = 8888

[functions]
  directory = "netlify/functions"

# Edge Functions
[[edge_functions]]
  path = "/api/card-reader"
  function = "card-reader"

# Yönlendirmeler
[[redirects]]
  from = "/api/card-reader"
  to = "/.netlify/edge-functions/card-reader"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/edge/*"
  to = "/.netlify/edge-functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# HTTP'yi koruyan özel davranış
[[headers]]
  for = "/api/card-reader"
  [headers.values]
    # HTTPS redirects'i kapatma
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
