[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "dist"

[dev]
  command = "npm run dev"
  targetPort = 8080
  port = 8888

[functions]
  directory = "netlify/functions"

# Edge Functions
[[edge_functions]]
  path = "/api/card-reader"
  function = "card-reader"

# Ana yönlendirme (hem domain hem IP için)
[[redirects]]
  from = "/api/card-reader"
  to = "/netlify/edge-functions/card-reader"
  status = 200
  force = true

# HTTP isteklerini HTTPS'e yönlendirmeyi engelle
[[redirects]]
  from = "http://ngsplus.app/api/card-reader"
  to = "/netlify/edge-functions/card-reader"
  status = 200
  force = true

# 3.124.100.143 IP adresi için yönlendirme
[[redirects]]
  from = "https://3.124.100.143/api/card-reader"
  to = "/netlify/edge-functions/card-reader"
  status = 200
  force = true
  
# 3.75.10.80 IP adresi için yönlendirme
[[redirects]]
  from = "https://3.75.10.80/api/card-reader"
  to = "/netlify/edge-functions/card-reader"
  status = 200
  force = true

# Genel API yönlendirmeleri
[[redirects]]
  from = "/api/*"
  to = "/netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/edge/*"
  to = "/netlify/edge-functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# HTTP başlık tanımlamaları
[[headers]]
  for = "/api/card-reader"
  [headers.values]
    # CORS ayarları
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    # SSL yönlendirmesi devre dışı
    Strict-Transport-Security = "max-age=0"
